### ISSUE TITLE
Use published version of swagger-node-runner

### ISSUE THREAD

**Issue by penx** [penx/openapi-mock#5]
Awaiting:

- [x] https://github.com/json-schema-faker/json-schema-faker/pull/360#issuecomment-364470410 release of json-schema-faker
- [x] apigee-127/sway#174 failing tests with json-schema-faker@0.5.0-rc13
- [x] apigee-127/sway#165 UNRESOLVABLE_REFERENCE for circular references
- [x] apigee-127/sway#168 Add date and time format support to mocks
- [x] apigee-127/sway#173 release of sway
- [x] theganyo/swagger-node-runner#119
- [x] theganyo/swagger-node-runner#121
- [ ] theganyo/swagger-node-runner#135
- [ ] theganyo/swagger-node-runner#136
